In [195]:
# SETUP LIBRARY DULU
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, classification_report
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.utils import class_weight

In [87]:
# PERSIAPAN DATA DAN SCALING MODEL PERTAMA

data = pd.read_csv("../content/Final_data.csv")
data.head()

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,...,cal_from_macros,pct_carbs,protein_per_kg,pct_HRR,pct_maxHR,cal_balance,lean_mass_kg,expected_burn,Burns Calories (per 30 min)_bc,Burns_Calories_Bin
0,34.91,Male,65.27,1.62,188.58,157.65,69.05,1.00,1080.90,Strength,...,2139.59,0.500432,1.624789,0.741237,0.835985,725.10,47.777394,685.1600,7.260425e+19,Medium
1,23.37,Female,56.41,1.55,179.43,131.75,73.18,1.37,1809.91,HIIT,...,1711.65,0.500850,1.514093,0.551247,0.734270,-232.91,40.809803,978.6184,1.020506e+20,High
2,33.20,Female,58.98,1.67,175.04,123.95,54.96,0.91,802.26,Cardio,...,1965.92,0.500610,1.663445,0.574534,0.708124,805.74,44.635580,654.5266,1.079607e+20,High
3,38.69,Female,93.78,1.70,191.21,155.10,50.07,1.10,1450.79,HIIT,...,1627.28,0.499533,0.862017,0.744155,0.811150,1206.21,63.007432,773.6300,8.987921e+19,High
4,45.09,Male,52.42,1.88,193.58,152.88,70.84,1.08,1166.40,Strength,...,2659.23,0.500581,2.538153,0.668405,0.789751,303.60,43.347504,711.4176,5.264685e+19,Low

In [88]:
data.columns

Index(['Age', 'Gender', 'Weight (kg)', 'Height (m)', 'Max_BPM', 'Avg_BPM',
       'Resting_BPM', 'Session_Duration (hours)', 'Calories_Burned',
       'Workout_Type', 'Fat_Percentage', 'Water_Intake (liters)',
       'Workout_Frequency (days/week)', 'Experience_Level', 'BMI',
       'Daily meals frequency', 'Physical exercise', 'Carbs', 'Proteins',
       'Fats', 'Calories', 'meal_name', 'meal_type', 'diet_type', 'sugar_g',
       'sodium_mg', 'cholesterol_mg', 'serving_size_g', 'cooking_method',
       'prep_time_min', 'cook_time_min', 'rating', 'Name of Exercise', 'Sets',
       'Reps', 'Benefit', 'Burns Calories (per 30 min)', 'Target Muscle Group',
       'Equipment Needed', 'Difficulty Level', 'Body Part', 'Type of Muscle',
       'Workout', 'BMI_calc', 'cal_from_macros', 'pct_carbs', 'protein_per_kg',
       'pct_HRR', 'pct_maxHR', 'cal_balance', 'lean_mass_kg', 'expected_burn',
       'Burns Calories (per 30 min)_bc', 'Burns_Calories_Bin'],
      dtype='object')

In [89]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 54 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             20000 non-null  float64
 1   Gender                          20000 non-null  object
 2   Weight (kg)                     20000 non-null  float64
 3   Height (m)                      20000 non-null  float64
 4   Max_BPM                         20000 non-null  float64
 5   Avg_BPM                         20000 non-null  float64
 6   Resting_BPM                     20000 non-null  float64
 7   Session_Duration (hours)        20000 non-null  float64
 8   Calories_Burned                 20000 non-null  float64
 9   Workout_Type                    20000 non-null  object
 10  Fat_Percentage                  20000 non-null  float64
 11  Water_Intake (liters)           20000 non-null  float64
 12  Workout_Frequency (days/week)   20000 non-null  float64
 13  Experience_Level                20000 non-null  float64
 14  BMI                             20000 non-null  float64
 15  Daily meals frequency           20000 non-null  float64
 16  Physical exercise               20000 non-null  float64
 17  Carbs                           20000 non-null  float64
 18  Proteins                        20000 non-null  float64
 19  Fats                            20000 non-null  float64
 20  Calories                        20000 non-null  float64
 21  meal_name                       20000 non-null  object
 22  meal_type                       20000 non-null  object
 23  diet_type                       20000 non-null  object
 24  sugar_g                         20000 non-null  float64
 25  sodium_mg                       20000 non-null  float64
 26  cholesterol_mg                  20000 non-null  float64
 27  serving_size_g                  20000 non-null  float64
 28  cooking_method                  20000 non-null  object
 29  prep_time_min                   20000 non-null  float64
 30  cook_time_min                   20000 non-null  float64
 31  rating                          20000 non-null  float64
 32  Name of Exercise                20000 non-null  object
 33  Sets                            20000 non-null  float64
 34  Reps                            20000 non-null  float64
 35  Benefit                         20000 non-null  object
 36  Burns Calories (per 30 min)     20000 non-null  float64
 37  Target Muscle Group             20000 non-null  object
 38  Equipment Needed                20000 non-null  object
 39  Difficulty Level                20000 non-null  object
 40  Body Part                       20000 non-null  object
 41  Type of Muscle                  20000 non-null  object
 42  Workout                         20000 non-null  object
 43  BMI_calc                        20000 non-null  float64
 44  cal_from_macros                 20000 non-null  float64
 45  pct_carbs                       20000 non-null  float64
 46  protein_per_kg                  20000 non-null  float64
 47  pct_HRR                         20000 non-null  float64
 48  pct_maxHR                       20000 non-null  float64
 49  cal_balance                     20000 non-null  float64
 50  lean_mass_kg                    20000 non-null  float64
 51  expected_burn                   20000 non-null  float64
 52  Burns Calories (per 30 min)_bc  20000 non-null  float64
 53  Burns_Calories_Bin              20000 non-null  object
dtypes: float64(39), object(15)
memory usage: 8.2+ MB

In [90]:
data.describe()

,Age,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Fat_Percentage,Water_Intake (liters),...,BMI_calc,cal_from_macros,pct_carbs,protein_per_kg,pct_HRR,pct_maxHR,cal_balance,lean_mass_kg,expected_burn,Burns Calories (per 30 min)_bc
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04
mean,38.851453,73.898832,1.723093,179.889702,143.704306,62.195813,1.259446,1280.109600,26.101313,2.627485,...,24.921651,1998.297076,0.499983,1.460142,0.699005,0.802305,744.308699,53.786384,866.352318,8.631802e+19
std,12.114580,21.173010,0.127033,11.510805,14.267688,7.289351,0.341336,502.228982,4.996160,0.604724,...,6.701144,440.848408,0.001455,0.518946,0.144880,0.096613,720.946619,12.498740,250.317069,3.197579e+19
min,18.000000,39.180000,1.490000,159.310000,119.070000,49.490000,0.490000,323.110000,11.333134,1.460000,...,12.037907,1105.570000,0.492434,0.516706,0.371344,0.599789,-1266.220000,30.946261,219.852800,2.491905e+16
25%,28.170000,58.160000,1.620000,170.057500,131.220000,55.960000,1.050000,910.800000,22.387807,2.170000,...,20.094975,1661.022500,0.499054,1.076294,0.583656,0.727676,261.432500,44.587037,714.098250,6.441978e+19
50%,39.865000,70.000000,1.710000,180.140000,142.990000,62.200000,1.270000,1231.450000,25.822504,2.610000,...,24.119097,1943.130000,0.499981,1.382260,0.686284,0.794834,691.190000,51.204908,868.721400,8.371578e+19
75%,49.630000,86.100000,1.800000,189.425000,156.060000,68.090000,1.460000,1553.112500,29.676026,3.120000,...,28.562620,2271.950000,0.500910,1.750495,0.798196,0.869211,1176.290000,61.939016,1012.532700,1.100442e+20
max,59.670000,130.770000,2.010000,199.640000,169.840000,74.500000,2.020000,2890.820000,35.000000,3.730000,...,50.229544,3699.540000,0.507889,3.916881,1.073939,1.047032,3075.580000,90.117371,1477.108800,1.756614e+20

In [132]:
# CLEANING DATA
median_non_neg = data[data['Physical exercise'] >= 0]['Physical exercise'].median()
data['Physical exercise'] = data['Physical exercise'].apply(lambda x: median_non_neg if x < 0 else x)

data['Physical exercise'].describe()

count    20000.000000
mean         0.464266
std          0.981135
min          0.000000
25%          0.010000
50%          0.020000
75%          0.040000
max          4.050000
Name: Physical exercise, dtype: float64

In [133]:
# ENCODING GENDER MENJADI BINER
data['Gender'] = data['Gender'].map({
    'Male' : 1,
    'Female' : 0
})

In [146]:
# MENDEFINISIKAN FITUR WAJIB (VARIABEL NUMERIK + VARIABEL KATEGORIKAL)
common_features = [
    'Age', 'Gender', 'Weight (kg)', 'Height (m)', 'BMI',
    'Workout_Frequency (days/week)', 'Session_Duration (hours)', 'Workout_Type',
    'Daily meals frequency', 'diet_type', 'Calories', 'Physical exercise'
]

available_features = [
    f for f in common_features if f in data.columns
]

X_common = data[availabe_features]
y_calories = data['Calories_Burned']

print("Fitur yang ada pada model pertama: \n",available_features)
print("\n✅ | Fitur utama yang digunakan totalnya ", len(available_features), available_features)

Fitur yang ada pada model pertama:
 ['Age', 'Gender', 'Weight (kg)', 'Height (m)', 'BMI', 'Workout_Frequency (days/week)', 'Session_Duration (hours)', 'Workout_Type', 'Daily meals frequency', 'diet_type', 'Calories', 'Physical exercise']

✅ | Fitur utama yang digunakan totalnya  12 ['Age', 'Gender', 'Weight (kg)', 'Height (m)', 'BMI', 'Workout_Frequency (days/week)', 'Session_Duration (hours)', 'Workout_Type', 'Daily meals frequency', 'diet_type', 'Calories', 'Physical exercise']

In [142]:
# ONE-HOT ENCODING KATEGORI
onehot_cols_common = ['Workout_Type', 'diet_type']
df_common_encoded = X_common.copy()

if onehot_cols_common :
  ohe_common = OneHotEncoder(sparse_output=False, drop='first')
  ohe_result_common = ohe_common.fit_transform(df_common_encoded[onehot_cols_common])
  ohe_df_common = pd.DataFrame(ohe_result_common, columns=ohe_common.get_feature_names_out(onehot_cols_common))

  df_common_encoded = df_common_encoded.drop(columns = onehot_cols_common).reset_index(drop = True).join(ohe_df_common.reset_index(drop = True))

In [144]:
# STANDARD SCALLER
numeric_cols_common = df_common_encoded.select_dtypes(include=['int64','float64']).columns.tolist()
categorical_cols_common = df_common_encoded.columns.difference(numerix_cols_common)

scaler_common = StandardScaler()
scaled_numeric_common = scaler_common.fit_transform(df_common_encoded[numeric_cols_common])
scaled_df_common = pd.DataFrame(scaled_numeric_common, columns=numeric_cols_common)

In [145]:
# FINAL FEATURES
X_common_processed = df_common_encoded[categorical_cols_common].reset_index(drop = True).join(scaled_df_common.reset_index(drop = True))
print(f"✅ | Data diproses! Total fitur akhir {X_common_processed.shape[1]}")

✅ | Data diproses! Total fitur akhir 17

In [149]:
# MEMBAGI DATA TRAIN DENGAN DATA VALIDASI DAN DATA TEST
X_cal_train, X_cal_temp, y_cal_train, y_cal_temp = train_test_split(
    X_common_processed, y_calories,
    test_size=0.4,
    random_state=42
)

X_cal_val, X_cal_test, y_cal_val, y_cal_test = train_test_split(
    X_cal_temp, y_cal_temp,
    test_size=0.5,
    random_state=42
)

print("🙏 | Split data kalori (train/ validation/ test) selesai")

🙏 | Split data kalori (train/ validation/ test) selesai

In [150]:
# MENDEFINISIKAN EARLY STOPPING
early_stopping = EarlyStopping(
    monitor = 'val_mae',
    patience = 15,
    restore_best_weights = True
)

In [151]:
# MEMBANGUNG ARSITEKTUR MODEL PERTAMA
model_pertama = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_cal_train.shape[1],)),
    Dropout(0.3),

    Dense(32, activation = 'relu'),
    Dropout(0.2),

    Dense(1)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [159]:
# COMPILE MODEL DENGAN LEARNING RATE = 0.0001
model_pertama.compile(
    optimizer = Adam(learning_rate = 0.001),
    loss = 'mse',
    metrics = ['mae']
)

model_pertama.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_16 (Dense)                │ (None, 64)             │         1,152 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_6 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_7 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,265 (12.75 KB)

 Trainable params: 3,265 (12.75 KB)

 Non-trainable params: 0 (0.00 B)

In [160]:
# TRAINING MODEL PERTAMA
print("\nTraining model pertama...")
history_cal = model_pertama.fit(
    X_cal_train, y_cal_train,
    validation_data = (X_cal_val, y_cal_val),
    epochs = 100,
    batch_size = 32,
    callbacks = [early_stopping],
    verbose = 1
)

Training model pertama...
Epoch 1/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 46353.1289 - mae: 164.8929 - val_loss: 5050.6934 - val_mae: 56.0738
Epoch 2/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46485.7383 - mae: 164.2096 - val_loss: 4189.0098 - val_mae: 51.3090
Epoch 3/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45420.5586 - mae: 162.9578 - val_loss: 4704.9253 - val_mae: 53.9897
Epoch 4/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45740.0156 - mae: 163.6266 - val_loss: 4039.2959 - val_mae: 50.3596
Epoch 5/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 45345.3867 - mae: 162.2968 - val_loss: 4925.8672 - val_mae: 56.0661
Epoch 6/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 41766.4922 - mae: 157.6839 - val_loss: 4355.6538 - val_mae: 51.9387
Epoch 7/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 46087.1172 - mae: 162.3785 - val_loss: 4112.3857 - val_mae: 49.9795
Epoch 8/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 42942.7578 - mae: 157.3040 - val_loss: 4296.7480 - val_mae: 51.6082
Epoch 9/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 43756.7852 - mae: 158.9334 - val_loss: 5227.0083 - val_mae: 56.3632
Epoch 10/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 41759.4492 - mae: 155.9596 - val_loss: 4559.4331 - val_mae: 52.0168
Epoch 11/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 43552.8906 - mae: 158.3706 - val_loss: 3737.7361 - val_mae: 47.9057
Epoch 12/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 42235.3984 - mae: 156.0648 - val_loss: 4329.9951 - val_mae: 51.7669
Epoch 13/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39848.2891 - mae: 151.6463 - val_loss: 4435.5869 - val_mae: 51.4713
Epoch 14/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 40339.3789 - mae: 152.7311 - val_loss: 4136.1240 - val_mae: 49.9447
Epoch 15/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 41622.1211 - mae: 154.1845 - val_loss: 3971.0430 - val_mae: 49.0841
Epoch 16/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 40463.9922 - mae: 151.9181 - val_loss: 4021.3887 - val_mae: 49.6308
Epoch 17/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 41241.6328 - mae: 152.1834 - val_loss: 3568.1470 - val_mae: 45.2523
Epoch 18/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 41760.4688 - mae: 153.8269 - val_loss: 4573.3789 - val_mae: 52.5051
Epoch 19/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 40113.4258 - mae: 152.4216 - val_loss: 5013.1260 - val_mae: 54.7971
Epoch 20/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39061.6953 - mae: 150.0954 - val_loss: 4076.4331 - val_mae: 49.5554
Epoch 21/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 40409.3750 - mae: 151.4117 - val_loss: 3411.9143 - val_mae: 46.0793
Epoch 22/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39412.5664 - mae: 150.4112 - val_loss: 5028.3911 - val_mae: 53.7969
Epoch 23/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 40606.8984 - mae: 150.6048 - val_loss: 3187.2546 - val_mae: 44.0555
Epoch 24/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39287.7812 - mae: 147.8923 - val_loss: 4090.1965 - val_mae: 48.6256
Epoch 25/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39761.2891 - mae: 149.4563 - val_loss: 3564.7869 - val_mae: 45.3333
Epoch 26/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 40455.0859 - mae: 150.3072 - val_loss: 3803.5735 - val_mae: 46.5279
Epoch 27/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - loss: 38332.6328 - mae: 146.3007 - val_loss: 3622.6548 - val_mae: 45.4653
Epoch 28/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 38853.2930 - mae: 147.7993 - val_loss: 3426.5952 - val_mae: 46.5688
Epoch 29/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38131.1328 - mae: 147.0949 - val_loss: 3599.9211 - val_mae: 45.5325
Epoch 30/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38260.0078 - mae: 147.8127 - val_loss: 4126.0400 - val_mae: 48.3241
Epoch 31/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37999.6875 - mae: 148.0027 - val_loss: 3567.1284 - val_mae: 45.1194
Epoch 32/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 40346.7734 - mae: 150.2385 - val_loss: 3171.7603 - val_mae: 43.1399
Epoch 33/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38853.3242 - mae: 147.1998 - val_loss: 4014.1018 - val_mae: 47.4148
Epoch 34/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37392.5938 - mae: 144.4092 - val_loss: 3250.2261 - val_mae: 45.1233
Epoch 35/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38227.3242 - mae: 146.4984 - val_loss: 3510.5955 - val_mae: 43.2776
Epoch 36/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38073.1523 - mae: 146.1443 - val_loss: 4026.9573 - val_mae: 48.4549
Epoch 37/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 38758.4922 - mae: 147.9349 - val_loss: 3889.7500 - val_mae: 45.7680
Epoch 38/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39397.4258 - mae: 147.0049 - val_loss: 3035.3486 - val_mae: 42.2073
Epoch 39/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37180.2070 - mae: 145.6284 - val_loss: 3350.0493 - val_mae: 42.8225
Epoch 40/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 39113.4102 - mae: 147.5447 - val_loss: 3121.4646 - val_mae: 42.9939
Epoch 41/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36994.4062 - mae: 144.9988 - val_loss: 3211.3328 - val_mae: 44.9877
Epoch 42/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35884.7188 - mae: 142.2852 - val_loss: 3209.7720 - val_mae: 44.1488
Epoch 43/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38217.8320 - mae: 146.9128 - val_loss: 3033.2402 - val_mae: 40.7694
Epoch 44/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37326.7695 - mae: 144.8976 - val_loss: 3772.7488 - val_mae: 45.0433
Epoch 45/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37395.8867 - mae: 144.4340 - val_loss: 2956.3123 - val_mae: 42.1932
Epoch 46/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 38225.7969 - mae: 146.2862 - val_loss: 3586.8555 - val_mae: 44.2018
Epoch 47/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 37597.7500 - mae: 143.0745 - val_loss: 3663.7546 - val_mae: 45.9021
Epoch 48/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 35650.5508 - mae: 141.4071 - val_loss: 3794.5435 - val_mae: 45.8497
Epoch 49/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 36889.4688 - mae: 144.0766 - val_loss: 3224.4685 - val_mae: 42.6419
Epoch 50/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37430.3945 - mae: 144.4393 - val_loss: 3130.7080 - val_mae: 41.5000
Epoch 51/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37616.5781 - mae: 144.5238 - val_loss: 2991.6814 - val_mae: 41.3960
Epoch 52/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 36463.6836 - mae: 142.6603 - val_loss: 3204.9785 - val_mae: 41.9559
Epoch 53/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36066.8867 - mae: 142.2609 - val_loss: 2839.3975 - val_mae: 40.6903
Epoch 54/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 37632.4688 - mae: 142.6816 - val_loss: 3479.8528 - val_mae: 43.9735
Epoch 55/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35446.8281 - mae: 141.0535 - val_loss: 3568.5125 - val_mae: 45.3275
Epoch 56/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35084.9336 - mae: 139.4453 - val_loss: 3027.1116 - val_mae: 41.5364
Epoch 57/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35741.3945 - mae: 141.9588 - val_loss: 3007.9651 - val_mae: 41.7709
Epoch 58/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 36234.0430 - mae: 141.5444 - val_loss: 3113.4761 - val_mae: 42.9003
Epoch 59/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 35620.4961 - mae: 139.8449 - val_loss: 2696.1912 - val_mae: 40.1427
Epoch 60/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36232.9648 - mae: 141.2269 - val_loss: 3373.5098 - val_mae: 43.7151
Epoch 61/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36683.3828 - mae: 143.1160 - val_loss: 3562.3650 - val_mae: 44.8770
Epoch 62/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34860.5312 - mae: 139.7014 - val_loss: 3200.5198 - val_mae: 43.0495
Epoch 63/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35495.5430 - mae: 140.0972 - val_loss: 2944.0493 - val_mae: 40.8993
Epoch 64/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34492.2266 - mae: 139.4168 - val_loss: 3039.6990 - val_mae: 42.7348
Epoch 65/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35379.9688 - mae: 139.8945 - val_loss: 2832.8213 - val_mae: 39.9142
Epoch 66/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35452.0000 - mae: 141.1178 - val_loss: 2332.2131 - val_mae: 37.0790
Epoch 67/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34533.3203 - mae: 137.4388 - val_loss: 2512.1763 - val_mae: 38.5826
Epoch 68/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 36866.1602 - mae: 143.5135 - val_loss: 3502.3596 - val_mae: 45.0252
Epoch 69/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 33966.3633 - mae: 138.6089 - val_loss: 2670.0645 - val_mae: 39.4628
Epoch 70/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 34107.9609 - mae: 137.2642 - val_loss: 2431.0212 - val_mae: 38.0004
Epoch 71/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34717.6055 - mae: 137.5604 - val_loss: 3187.8340 - val_mae: 42.0832
Epoch 72/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34046.8242 - mae: 137.4938 - val_loss: 2629.5105 - val_mae: 39.1077
Epoch 73/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35471.9414 - mae: 140.3619 - val_loss: 2695.6052 - val_mae: 39.8375
Epoch 74/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34158.6680 - mae: 136.7715 - val_loss: 3696.8059 - val_mae: 44.7846
Epoch 75/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34776.6836 - mae: 138.7990 - val_loss: 2469.8984 - val_mae: 38.8436
Epoch 76/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34092.0664 - mae: 137.9914 - val_loss: 2470.4314 - val_mae: 38.7623
Epoch 77/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33601.9688 - mae: 136.8414 - val_loss: 3178.7424 - val_mae: 42.2950
Epoch 78/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 35087.3633 - mae: 138.3230 - val_loss: 2552.5403 - val_mae: 39.1879
Epoch 79/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33399.1484 - mae: 135.0698 - val_loss: 2957.4893 - val_mae: 41.7108
Epoch 80/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 33945.3008 - mae: 137.7673 - val_loss: 2260.4417 - val_mae: 36.7902
Epoch 81/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 33617.0195 - mae: 136.3901 - val_loss: 3598.0779 - val_mae: 45.4079
Epoch 82/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33017.8203 - mae: 135.1490 - val_loss: 2803.3560 - val_mae: 41.0843
Epoch 83/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34298.3828 - mae: 138.1973 - val_loss: 2503.9287 - val_mae: 37.7626
Epoch 84/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 32818.2617 - mae: 134.5643 - val_loss: 2672.0991 - val_mae: 39.3691
Epoch 85/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34087.9180 - mae: 135.8768 - val_loss: 3229.3599 - val_mae: 43.2845
Epoch 86/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33015.6523 - mae: 135.2295 - val_loss: 3135.1646 - val_mae: 43.0227
Epoch 87/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34117.5547 - mae: 136.8323 - val_loss: 2261.7124 - val_mae: 36.4126
Epoch 88/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33474.7695 - mae: 135.8552 - val_loss: 3010.4106 - val_mae: 41.3203
Epoch 89/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33095.9766 - mae: 135.4400 - val_loss: 2567.6958 - val_mae: 39.1926
Epoch 90/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 32337.7070 - mae: 134.0740 - val_loss: 2721.8179 - val_mae: 39.8487
Epoch 91/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 33228.4375 - mae: 134.3863 - val_loss: 2687.2917 - val_mae: 40.0649
Epoch 92/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33386.7344 - mae: 135.7861 - val_loss: 2495.3740 - val_mae: 37.9930
Epoch 93/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 33006.4844 - mae: 133.0861 - val_loss: 4122.3423 - val_mae: 49.0092
Epoch 94/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34122.6445 - mae: 135.7893 - val_loss: 3179.5740 - val_mae: 43.4886
Epoch 95/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 32086.7188 - mae: 134.3850 - val_loss: 2428.3962 - val_mae: 38.4384
Epoch 96/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34430.8555 - mae: 136.7359 - val_loss: 2966.4688 - val_mae: 40.6129
Epoch 97/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 32681.2344 - mae: 134.5722 - val_loss: 2524.3545 - val_mae: 39.2903
Epoch 98/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 32026.9395 - mae: 132.1183 - val_loss: 2642.5947 - val_mae: 38.9873
Epoch 99/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 32446.6328 - mae: 134.1020 - val_loss: 2478.4492 - val_mae: 38.4252
Epoch 100/100
375/375 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31289.9570 - mae: 132.7973 - val_loss: 2476.1130 - val_mae: 38.0893

In [161]:
# EVALUASI MODEL DENGAN DATA TEST
y_cal_pred = model_pertama.predict(X_cal_test)
mae_cal = mean_absolute_error(y_cal_test, y_cal_pred)
r2_cal = r2_score(y_cal_test, y_cal_pred)

print("\n ==== HASIL AKHIR MAE & R2 MODEL PERTAMA ====")
print(f"Mean Absolute Error (MAE): {mae_cal:.2f}")
print(f"R2 Score: {r2_cal:.4f}")

125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

 ==== HASIL AKHIR MAE & R2 MODEL PERTAMA ====
Mean Absolute Error (MAE): 35.87
R2 Score: 0.9913

In [164]:
# TAMBAH LAYER
model_pertama_tuned = Sequential([
    Dense(128, activation = 'relu', input_shape = (X_cal_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation = 'relu'),
    Dropout(0.2),
    Dense(32, activation = 'relu'),
    Dropout(0.2),
    Dense(1)
])

model_pertama_tuned.compile(
    optimizer = Adam(learning_rate = 0.001),
    loss = 'mse',
    metrics = ['mae']
)

model_dnn_pertama_tuned.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,109 (27.77 KB)

 Trainable params: 2,369 (9.25 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 4,740 (18.52 KB)

In [167]:
history_cal_tuned = model_pertama_tuned.fit(
    X_cal_train, y_cal_train,
    validation_data = (X_cal_val, y_cal_val),
    epochs = 100,
    batch_size = 32,
    verbose = 2
)

y_cal_pred_tuned = model_pertama_tuned.predict(X_cal_test)
mae_cal_tuned = mean_absolute_error(y_cal_test, y_cal_pred_tuned)
mse_cal_tuned = mean_squared_error(y_cal_test, y_cal_pred_tuned)
r2_cal_tuned = r2_score(y_cal_test, y_cal_pred_tuned)

print("\n==== EVALUASI HASIL MODEL PERTAMA SETELAH DITUNING ====")
print(f"Mean Absolute Error (MAE): {mae_cal_tuned:.2f}")
print(f"Mean Squared Error (MSE): {mse_cal_tuned:.2f}")
print(f"R2 Score: {r2_cal_tuned:.4f}")

Epoch 1/100
375/375 - 2s - 6ms/step - loss: 36021.8477 - mae: 141.1859 - val_loss: 4481.8125 - val_mae: 51.7767
Epoch 2/100
375/375 - 2s - 5ms/step - loss: 37467.5703 - mae: 143.3808 - val_loss: 7644.3726 - val_mae: 69.9229
Epoch 3/100
375/375 - 1s - 4ms/step - loss: 35940.5859 - mae: 140.9026 - val_loss: 2362.2385 - val_mae: 37.5128
Epoch 4/100
375/375 - 1s - 3ms/step - loss: 34816.4336 - mae: 139.0045 - val_loss: 1970.9432 - val_mae: 34.7100
Epoch 5/100
375/375 - 1s - 3ms/step - loss: 34833.2812 - mae: 138.7968 - val_loss: 4045.8142 - val_mae: 49.8349
Epoch 6/100
375/375 - 1s - 3ms/step - loss: 35890.3906 - mae: 140.9886 - val_loss: 5464.7017 - val_mae: 57.1578
Epoch 7/100
375/375 - 1s - 3ms/step - loss: 35493.2734 - mae: 140.7077 - val_loss: 2365.2788 - val_mae: 38.2489
Epoch 8/100
375/375 - 1s - 3ms/step - loss: 34846.3164 - mae: 138.8690 - val_loss: 2644.7737 - val_mae: 40.4321
Epoch 9/100
375/375 - 1s - 3ms/step - loss: 34942.0664 - mae: 138.9185 - val_loss: 1819.2081 - val_mae: 33.3676
Epoch 10/100
375/375 - 1s - 3ms/step - loss: 35065.1602 - mae: 138.9639 - val_loss: 4404.7930 - val_mae: 51.6722
Epoch 11/100
375/375 - 1s - 3ms/step - loss: 35168.2461 - mae: 139.3025 - val_loss: 1817.0612 - val_mae: 32.9582
Epoch 12/100
375/375 - 1s - 3ms/step - loss: 34205.7578 - mae: 137.7317 - val_loss: 2556.3870 - val_mae: 39.3346
Epoch 13/100
375/375 - 2s - 4ms/step - loss: 36416.9375 - mae: 141.0265 - val_loss: 2717.4346 - val_mae: 40.7713
Epoch 14/100
375/375 - 1s - 4ms/step - loss: 34972.4766 - mae: 138.2161 - val_loss: 2681.7400 - val_mae: 39.7304
Epoch 15/100
375/375 - 1s - 3ms/step - loss: 33798.3945 - mae: 137.1089 - val_loss: 2158.2307 - val_mae: 36.2226
Epoch 16/100
375/375 - 1s - 3ms/step - loss: 35184.0781 - mae: 138.9039 - val_loss: 3225.1404 - val_mae: 43.1922
Epoch 17/100
375/375 - 1s - 3ms/step - loss: 34713.5117 - mae: 139.0573 - val_loss: 2778.3696 - val_mae: 40.3288
Epoch 18/100
375/375 - 1s - 3ms/step - loss: 35118.1367 - mae: 140.3184 - val_loss: 4039.8257 - val_mae: 50.6142
Epoch 19/100
375/375 - 1s - 3ms/step - loss: 34936.9062 - mae: 138.1938 - val_loss: 3493.4006 - val_mae: 46.6720
Epoch 20/100
375/375 - 1s - 3ms/step - loss: 34212.0898 - mae: 137.5310 - val_loss: 2507.5361 - val_mae: 38.5622
Epoch 21/100
375/375 - 1s - 3ms/step - loss: 34570.3672 - mae: 137.7635 - val_loss: 6695.1367 - val_mae: 63.3516
Epoch 22/100
375/375 - 1s - 3ms/step - loss: 35139.0625 - mae: 138.9336 - val_loss: 3312.5315 - val_mae: 45.3298
Epoch 23/100
375/375 - 1s - 3ms/step - loss: 34538.6406 - mae: 137.9784 - val_loss: 2457.0840 - val_mae: 39.0963
Epoch 24/100
375/375 - 1s - 3ms/step - loss: 35605.4648 - mae: 138.9735 - val_loss: 2111.0176 - val_mae: 35.8009
Epoch 25/100
375/375 - 2s - 4ms/step - loss: 34292.6992 - mae: 137.2239 - val_loss: 2048.4849 - val_mae: 35.5939
Epoch 26/100
375/375 - 1s - 3ms/step - loss: 35325.5938 - mae: 139.1886 - val_loss: 2454.2788 - val_mae: 38.6142
Epoch 27/100
375/375 - 1s - 3ms/step - loss: 34774.1367 - mae: 138.1155 - val_loss: 2514.0410 - val_mae: 38.5445
Epoch 28/100
375/375 - 1s - 3ms/step - loss: 35270.7773 - mae: 139.9720 - val_loss: 2342.4055 - val_mae: 36.3585
Epoch 29/100
375/375 - 1s - 3ms/step - loss: 33638.0625 - mae: 136.6293 - val_loss: 1768.6992 - val_mae: 32.7468
Epoch 30/100
375/375 - 1s - 3ms/step - loss: 34859.2539 - mae: 138.3015 - val_loss: 1998.3688 - val_mae: 35.2531
Epoch 31/100
375/375 - 1s - 3ms/step - loss: 34716.2930 - mae: 138.3195 - val_loss: 2140.7778 - val_mae: 36.2541
Epoch 32/100
375/375 - 1s - 3ms/step - loss: 34544.4141 - mae: 138.7101 - val_loss: 2536.2993 - val_mae: 39.8262
Epoch 33/100
375/375 - 1s - 3ms/step - loss: 34664.7266 - mae: 137.8395 - val_loss: 2571.5518 - val_mae: 38.8443
Epoch 34/100
375/375 - 1s - 3ms/step - loss: 34493.0898 - mae: 138.4508 - val_loss: 3597.2559 - val_mae: 46.6409
Epoch 35/100
375/375 - 1s - 3ms/step - loss: 33818.5430 - mae: 137.0054 - val_loss: 3529.9827 - val_mae: 45.6216
Epoch 36/100
375/375 - 1s - 4ms/step - loss: 34496.4336 - mae: 137.7055 - val_loss: 1858.7750 - val_mae: 33.4237
Epoch 37/100
375/375 - 2s - 4ms/step - loss: 33919.4570 - mae: 137.0981 - val_loss: 4895.9097 - val_mae: 54.4531
Epoch 38/100
375/375 - 2s - 5ms/step - loss: 33948.6250 - mae: 136.8667 - val_loss: 4367.0220 - val_mae: 51.6720
Epoch 39/100
375/375 - 1s - 3ms/step - loss: 34259.4688 - mae: 137.5450 - val_loss: 1971.0453 - val_mae: 34.3141
Epoch 40/100
375/375 - 1s - 3ms/step - loss: 34274.9688 - mae: 137.5577 - val_loss: 4239.6768 - val_mae: 49.8397
Epoch 41/100
375/375 - 1s - 3ms/step - loss: 35245.1367 - mae: 139.1499 - val_loss: 1971.1990 - val_mae: 34.3593
Epoch 42/100
375/375 - 1s - 3ms/step - loss: 34500.5391 - mae: 137.8204 - val_loss: 3997.6121 - val_mae: 48.2084
Epoch 43/100
375/375 - 1s - 3ms/step - loss: 35022.0430 - mae: 139.0679 - val_loss: 2299.4829 - val_mae: 36.6498
Epoch 44/100
375/375 - 1s - 3ms/step - loss: 34647.2148 - mae: 138.4861 - val_loss: 1847.5543 - val_mae: 33.4929
Epoch 45/100
375/375 - 1s - 3ms/step - loss: 34094.4570 - mae: 137.8254 - val_loss: 2350.3618 - val_mae: 38.0019
Epoch 46/100
375/375 - 2s - 4ms/step - loss: 34034.1445 - mae: 136.5867 - val_loss: 4545.1328 - val_mae: 52.6589
Epoch 47/100
375/375 - 2s - 4ms/step - loss: 33458.3242 - mae: 136.1524 - val_loss: 2121.2185 - val_mae: 35.9571
Epoch 48/100
375/375 - 1s - 3ms/step - loss: 32950.7422 - mae: 134.8101 - val_loss: 1974.1824 - val_mae: 34.8520
Epoch 49/100
375/375 - 1s - 3ms/step - loss: 34851.7227 - mae: 138.6088 - val_loss: 2912.0264 - val_mae: 40.8237
Epoch 50/100
375/375 - 1s - 3ms/step - loss: 34585.7109 - mae: 137.7322 - val_loss: 2951.1934 - val_mae: 42.0247
Epoch 51/100
375/375 - 1s - 3ms/step - loss: 34569.7969 - mae: 137.4417 - val_loss: 2386.7839 - val_mae: 37.6206
Epoch 52/100
375/375 - 1s - 3ms/step - loss: 34951.4727 - mae: 139.1257 - val_loss: 4999.4717 - val_mae: 53.1876
Epoch 53/100
375/375 - 1s - 3ms/step - loss: 32986.1992 - mae: 135.3426 - val_loss: 2486.2756 - val_mae: 38.4505
Epoch 54/100
375/375 - 1s - 3ms/step - loss: 33870.9141 - mae: 137.5513 - val_loss: 1924.5323 - val_mae: 34.1753
Epoch 55/100
375/375 - 1s - 3ms/step - loss: 34605.3555 - mae: 137.4572 - val_loss: 2775.0891 - val_mae: 39.4685
Epoch 56/100
375/375 - 1s - 3ms/step - loss: 34542.9570 - mae: 138.0648 - val_loss: 2541.2874 - val_mae: 38.7432
Epoch 57/100
375/375 - 2s - 4ms/step - loss: 33657.0547 - mae: 136.5347 - val_loss: 1973.6427 - val_mae: 34.3249
Epoch 58/100
375/375 - 1s - 4ms/step - loss: 34230.2578 - mae: 137.5418 - val_loss: 4482.3130 - val_mae: 52.5332
Epoch 59/100
375/375 - 1s - 3ms/step - loss: 34554.7539 - mae: 138.4319 - val_loss: 1958.0114 - val_mae: 34.9632
Epoch 60/100
375/375 - 1s - 3ms/step - loss: 34528.0586 - mae: 137.9256 - val_loss: 3649.7207 - val_mae: 47.4860
Epoch 61/100
375/375 - 1s - 3ms/step - loss: 33880.5859 - mae: 136.6416 - val_loss: 2184.2336 - val_mae: 35.7807
Epoch 62/100
375/375 - 1s - 3ms/step - loss: 33610.0547 - mae: 136.7607 - val_loss: 3911.4602 - val_mae: 49.0520
Epoch 63/100
375/375 - 1s - 3ms/step - loss: 34872.9648 - mae: 138.4313 - val_loss: 3644.9773 - val_mae: 46.7644
Epoch 64/100
375/375 - 1s - 3ms/step - loss: 34747.5391 - mae: 137.8884 - val_loss: 2060.0146 - val_mae: 35.0373
Epoch 65/100
375/375 - 1s - 3ms/step - loss: 33451.7305 - mae: 136.2365 - val_loss: 3049.8071 - val_mae: 41.6371
Epoch 66/100
375/375 - 1s - 3ms/step - loss: 34359.2773 - mae: 137.8353 - val_loss: 2411.7134 - val_mae: 38.3021
Epoch 67/100
375/375 - 1s - 3ms/step - loss: 34688.6445 - mae: 137.8970 - val_loss: 2826.4097 - val_mae: 40.2489
Epoch 68/100
375/375 - 2s - 4ms/step - loss: 34248.1641 - mae: 137.4432 - val_loss: 1803.5582 - val_mae: 32.9823
Epoch 69/100
375/375 - 2s - 5ms/step - loss: 33387.2500 - mae: 135.0055 - val_loss: 2431.8635 - val_mae: 38.5816
Epoch 70/100
375/375 - 1s - 3ms/step - loss: 33900.8125 - mae: 137.1909 - val_loss: 3423.1458 - val_mae: 45.3511
Epoch 71/100
375/375 - 1s - 3ms/step - loss: 34560.3242 - mae: 138.0444 - val_loss: 3534.0066 - val_mae: 45.9170
Epoch 72/100
375/375 - 1s - 3ms/step - loss: 34095.0508 - mae: 137.1355 - val_loss: 1934.8025 - val_mae: 34.5751
Epoch 73/100
375/375 - 1s - 3ms/step - loss: 33623.7188 - mae: 136.8161 - val_loss: 2781.3889 - val_mae: 40.5011
Epoch 74/100
375/375 - 1s - 3ms/step - loss: 33559.8359 - mae: 136.4943 - val_loss: 2311.7712 - val_mae: 37.7200
Epoch 75/100
375/375 - 1s - 3ms/step - loss: 33595.2969 - mae: 135.8078 - val_loss: 2658.9590 - val_mae: 40.3223
Epoch 76/100
375/375 - 1s - 3ms/step - loss: 33684.7617 - mae: 136.5917 - val_loss: 3459.5054 - val_mae: 46.1692
Epoch 77/100
375/375 - 1s - 3ms/step - loss: 32872.4258 - mae: 134.6260 - val_loss: 1944.0797 - val_mae: 34.2178
Epoch 78/100
375/375 - 1s - 4ms/step - loss: 33846.5938 - mae: 136.5315 - val_loss: 2147.7393 - val_mae: 36.5896
Epoch 79/100
375/375 - 1s - 4ms/step - loss: 33158.7734 - mae: 135.5574 - val_loss: 1812.6650 - val_mae: 33.2204
Epoch 80/100
375/375 - 1s - 3ms/step - loss: 33890.7969 - mae: 137.1466 - val_loss: 1884.4399 - val_mae: 33.9919
Epoch 81/100
375/375 - 1s - 3ms/step - loss: 33578.0000 - mae: 136.1350 - val_loss: 2815.4294 - val_mae: 41.7775
Epoch 82/100
375/375 - 1s - 3ms/step - loss: 33457.9688 - mae: 136.0073 - val_loss: 2896.6221 - val_mae: 42.3591
Epoch 83/100
375/375 - 1s - 3ms/step - loss: 33739.8359 - mae: 136.7201 - val_loss: 1957.6006 - val_mae: 34.7899
Epoch 84/100
375/375 - 1s - 3ms/step - loss: 33190.1992 - mae: 135.5999 - val_loss: 2424.0349 - val_mae: 38.5086
Epoch 85/100
375/375 - 1s - 3ms/step - loss: 34389.2891 - mae: 137.2004 - val_loss: 2688.2122 - val_mae: 40.3522
Epoch 86/100
375/375 - 1s - 3ms/step - loss: 32753.0801 - mae: 134.5791 - val_loss: 5773.7168 - val_mae: 60.0747
Epoch 87/100
375/375 - 1s - 3ms/step - loss: 33321.4531 - mae: 135.1275 - val_loss: 3068.5305 - val_mae: 42.3295
Epoch 88/100
375/375 - 1s - 3ms/step - loss: 32906.0977 - mae: 134.7713 - val_loss: 2929.2505 - val_mae: 42.2740
Epoch 89/100
375/375 - 1s - 3ms/step - loss: 33419.0781 - mae: 135.8617 - val_loss: 2548.8577 - val_mae: 38.5759
Epoch 90/100
375/375 - 2s - 4ms/step - loss: 32819.5078 - mae: 135.3967 - val_loss: 2792.8342 - val_mae: 40.9350
Epoch 91/100
375/375 - 1s - 3ms/step - loss: 33403.7383 - mae: 135.2316 - val_loss: 3559.2673 - val_mae: 46.1331
Epoch 92/100
375/375 - 1s - 3ms/step - loss: 32511.0605 - mae: 134.3993 - val_loss: 2505.0103 - val_mae: 38.5723
Epoch 93/100
375/375 - 1s - 3ms/step - loss: 33435.4023 - mae: 135.6293 - val_loss: 1991.3944 - val_mae: 34.7180
Epoch 94/100
375/375 - 1s - 3ms/step - loss: 33891.6641 - mae: 136.0340 - val_loss: 2636.7012 - val_mae: 39.5940
Epoch 95/100
375/375 - 1s - 3ms/step - loss: 33075.6836 - mae: 135.6160 - val_loss: 2322.0662 - val_mae: 37.3879
Epoch 96/100
375/375 - 1s - 3ms/step - loss: 33931.5430 - mae: 136.6937 - val_loss: 3973.6377 - val_mae: 49.2822
Epoch 97/100
375/375 - 1s - 3ms/step - loss: 34140.3398 - mae: 135.6827 - val_loss: 1894.3417 - val_mae: 33.9664
Epoch 98/100
375/375 - 1s - 3ms/step - loss: 33153.5898 - mae: 135.2683 - val_loss: 2087.3743 - val_mae: 35.6152
Epoch 99/100
375/375 - 1s - 3ms/step - loss: 32263.7129 - mae: 133.2231 - val_loss: 2048.0330 - val_mae: 35.5472
Epoch 100/100
375/375 - 1s - 3ms/step - loss: 33645.5820 - mae: 135.4403 - val_loss: 2509.1357 - val_mae: 39.4120
125/125 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

==== EVALUASI HASIL MODEL PERTAMA SETELAH DITUNING ====
Mean Absolute Error (MAE): 39.47
Mean Squared Error (MSE): 2520.81
R2 Score: 0.9900

In [169]:
# PENGAMBILAN DATA UNTUK MODEL KEDUA
le = LabelEncoder()
data['Workout_Type_Encoded'] = le.fit_transform(data['Workout_Type'])
numeric_class = len(le.classes_)
y_cls_oh = to_categorical(data['Workout_Type_Encoded'])

# MENDEFINISIKAN FEATURES X_cls
cols_to_drop = [col for col in X_common_processed.columns if 'Workout_Type_' in col]
X_cls = X_common_processed.drop(columns = cols_to_drop)

print(f"✅ | Features Klasifikasi yang disiapkan, totalnya : {X_cls.shape[1]}")

✅ | Features Klasifikasi yang disiapkan, totalnya : 14

In [170]:
# MEMBAGI DATA
X_cls_train, X_cls_test, y_cls_train, y_cls_test = train_test_split(
    X_cls, y_cls_oh,
    test_size = 0.2,
    random_state = 42,
    stratify = data['Workout_Type_Encoded']
)

In [202]:
# MEMBANGUN ARSITEKTUR MODEL KEDUA
early_stopping_cls = EarlyStopping(
    monitor = 'val_accuracy',
    patience = 15,
    restore_best_weights = True
)

input_dim_cls = X_cls_train.shape[1]

model_kedua = Sequential([
    Dense(128, activation = 'relu', input_shape = (input_dim_cls,)),
    Dropout(0.3),

    Dense(64, activation = 'relu'),
    Dropout(0.2),

    Dense(numeric_class, activation = 'softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [204]:
# COMPILE MODEL KEDUA
model_kedua.compile(
    optimizer = Adam(learning_rate = 0.001),
    loss = 'categorical_crossentropy',
    metrics = ['accuracy']
)

model_kedua.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_40 (Dense)                │ (None, 128)            │         1,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_22 (Dropout)            │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_41 (Dense)                │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_23 (Dropout)            │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_42 (Dense)                │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,436 (40.77 KB)

 Trainable params: 10,436 (40.77 KB)

 Non-trainable params: 0 (0.00 B)

In [201]:
# TRAINING MODEL KEDUA
y_train_labels = np.argmax(y_cls_train, axis = 1)
class_weights = class_weight.compute_class_weight(
    class_weight = 'balanced',
    classes = np.unique(y_train_labels),
    y = y_train_labels
)

class_weight_dict = dict(enumerate(class_weights))
print("Bobot kelas untuk model klasifikasi: ", class_weight_dict)

print("\nTraining model kedua ...")
history_cls = model_kedua.fit(
    X_cls_train, y_cls_train,
    epochs = 200,
    batch_size = 32,
    callbacks = [early_stopping_cls],
    class_weight = class_weight_dict,
    validation_split = 0.2,
    verbose = 1
)

Bobot kelas untuk model klasifikasi:  {0: np.float64(1.015744032503809), 1: np.float64(1.0052777079668258), 2: np.float64(0.9859502095144195), 3: np.float64(0.9935419771485345)}

Training model kedua ...
Epoch 1/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.2472 - loss: 1.4374 - val_accuracy: 0.2497 - val_loss: 1.3903
Epoch 2/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2487 - loss: 1.3939 - val_accuracy: 0.2528 - val_loss: 1.3875
Epoch 3/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2591 - loss: 1.3885 - val_accuracy: 0.2506 - val_loss: 1.3871
Epoch 4/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2693 - loss: 1.3864 - val_accuracy: 0.2428 - val_loss: 1.3873
Epoch 5/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2699 - loss: 1.3853 - val_accuracy: 0.2491 - val_loss: 1.3874
Epoch 6/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2762 - loss: 1.3840 - val_accuracy: 0.2431 - val_loss: 1.3875
Epoch 7/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2742 - loss: 1.3839 - val_accuracy: 0.2512 - val_loss: 1.3866
Epoch 8/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2761 - loss: 1.3825 - val_accuracy: 0.2488 - val_loss: 1.3877
Epoch 9/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.2707 - loss: 1.3852 - val_accuracy: 0.2362 - val_loss: 1.3882
Epoch 10/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2756 - loss: 1.3829 - val_accuracy: 0.2562 - val_loss: 1.3870
Epoch 11/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2770 - loss: 1.3835 - val_accuracy: 0.2456 - val_loss: 1.3875
Epoch 12/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2758 - loss: 1.3809 - val_accuracy: 0.2441 - val_loss: 1.3886
Epoch 13/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.2747 - loss: 1.3819 - val_accuracy: 0.2453 - val_loss: 1.3883
Epoch 14/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2823 - loss: 1.3798 - val_accuracy: 0.2459 - val_loss: 1.3884
Epoch 15/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2841 - loss: 1.3811 - val_accuracy: 0.2428 - val_loss: 1.3884
Epoch 16/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.2862 - loss: 1.3791 - val_accuracy: 0.2441 - val_loss: 1.3883
Epoch 17/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.2712 - loss: 1.3814 - val_accuracy: 0.2488 - val_loss: 1.3884
Epoch 18/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.2926 - loss: 1.3775 - val_accuracy: 0.2450 - val_loss: 1.3895
Epoch 19/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2796 - loss: 1.3798 - val_accuracy: 0.2441 - val_loss: 1.3898
Epoch 20/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.2822 - loss: 1.3764 - val_accuracy: 0.2463 - val_loss: 1.3887
Epoch 21/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2821 - loss: 1.3783 - val_accuracy: 0.2419 - val_loss: 1.3886
Epoch 22/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2962 - loss: 1.3759 - val_accuracy: 0.2456 - val_loss: 1.3888
Epoch 23/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2941 - loss: 1.3772 - val_accuracy: 0.2463 - val_loss: 1.3902
Epoch 24/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.2835 - loss: 1.3769 - val_accuracy: 0.2497 - val_loss: 1.3892
Epoch 25/200
400/400 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.2840 - loss: 1.3761 - val_accuracy: 0.2400 - val_loss: 1.3899

In [205]:
# EVALUASI MODEL KEDUA
loss_cls, accuracy_cls = model_kedua.evaluate(X_cls_test, y_cls_test, verbose = 0)
print(f"\nLoss model kedua: {loss_cls:.4f}")
print(f"💀 | Akurasi model kedua: {accuracy_cls:.4f}")

Loss model kedua: 1.4710
💀 | Akurasi model kedua: 0.2570

In [208]:
# LAPORAN KLASIFIKASI
y_cls_pred_probs = model_kedua.predict(X_cls_test, verbose = 0)
y_cls_pred_probs_encoded= np.argmax(y_cls_pred_probs, axis = 1)

print("\n==== LAPORAN KLASIFIKASI ====")
print(classification_report(np.argmax(y_cls_test, axis = 1), y_cls_pred_probs_encoded, target_names = le.classes_))

==== LAPORAN KLASIFIKASI ====
              precision    recall  f1-score   support

      Cardio       0.25      0.31      0.28       985
        HIIT       0.27      0.20      0.23       995
    Strength       0.00      0.00      0.00      1014
        Yoga       0.26      0.52      0.34      1006

    accuracy                           0.26      4000
   macro avg       0.19      0.26      0.21      4000
weighted avg       0.19      0.26      0.21      4000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))